# If you've like to contribute to my Master's Degree Slush Fund, so I can take this to the next level:

github: https://github.com/sponsors/qikevinl
thanks_dev: https://thanks.dev/e/gh/qikevinl
patreon: hhttps://www.patreon.com/cw/qikevinl
buy_me_a_coffee: https://buymeacoffee.com/qikevinl
