"""
Action Potential Propagation
Generated by LearnViz

Visualizes how an action potential travels along an axon.
"""
from manim import *
import numpy as np

class ActionPotentialScene(Scene):
    def construct(self):
        # Title
        title = Text("Action Potential Propagation", font_size=42)
        subtitle = Text("How neurons transmit electrical signals", font_size=24, color=GRAY)
        subtitle.next_to(title, DOWN)

        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)
        self.play(FadeOut(title), FadeOut(subtitle))

        # Create neuron structure
        self.show_neuron_structure()
        self.wait(1)

        # Show resting potential
        self.show_resting_potential()
        self.wait(1)

        # Animate action potential
        self.animate_action_potential()
        self.wait(1)

        # Show voltage graph
        self.show_voltage_graph()
        self.wait(2)

    def show_neuron_structure(self):
        # Cell body (soma)
        self.soma = Circle(radius=0.6, fill_opacity=0.7, fill_color=BLUE, stroke_color=WHITE)
        self.soma.shift(LEFT * 5)
        soma_label = Text("Soma", font_size=18).next_to(self.soma, DOWN)

        # Axon (long cylinder representation)
        self.axon = Rectangle(width=8, height=0.4, fill_opacity=0.5, fill_color=BLUE_E, stroke_color=WHITE)
        self.axon.next_to(self.soma, RIGHT, buff=0)

        # Axon terminal
        self.terminal = Circle(radius=0.3, fill_opacity=0.7, fill_color=BLUE, stroke_color=WHITE)
        self.terminal.next_to(self.axon, RIGHT, buff=0)
        terminal_label = Text("Terminal", font_size=18).next_to(self.terminal, DOWN)

        # Myelin sheaths (segments)
        self.myelin_sheaths = VGroup()
        for i in range(4):
            sheath = Rectangle(width=1.5, height=0.6, fill_opacity=0.3, fill_color=YELLOW, stroke_color=YELLOW)
            sheath.move_to(self.axon.get_center() + LEFT * 2.5 + RIGHT * i * 2)
            self.myelin_sheaths.add(sheath)

        myelin_label = Text("Myelin Sheath", font_size=16, color=YELLOW)
        myelin_label.next_to(self.myelin_sheaths[1], UP)

        # Node of Ranvier labels
        node_label = Text("Node of Ranvier", font_size=14, color=RED)
        node_label.next_to(self.axon, UP).shift(LEFT * 1.5)
        node_arrow = Arrow(node_label.get_bottom(), self.axon.get_top() + LEFT * 1.5, color=RED, buff=0.1)

        self.play(
            Create(self.soma), Write(soma_label),
            Create(self.axon),
            Create(self.terminal), Write(terminal_label)
        )
        self.play(
            Create(self.myelin_sheaths),
            Write(myelin_label)
        )
        self.play(Write(node_label), Create(node_arrow))

        # Store for later
        self.neuron_group = VGroup(self.soma, self.axon, self.terminal, self.myelin_sheaths)

    def show_resting_potential(self):
        # Resting potential explanation
        rest_text = Text("Resting Potential: -70mV", font_size=28)
        rest_text.to_edge(UP)

        # Show charge distribution
        plus_outside = VGroup(*[
            Text("+", font_size=20, color=RED).move_to(self.axon.get_top() + UP * 0.3 + LEFT * 3 + RIGHT * i * 1.5)
            for i in range(5)
        ])
        minus_inside = VGroup(*[
            Text("-", font_size=20, color=BLUE).move_to(self.axon.get_center() + LEFT * 3 + RIGHT * i * 1.5)
            for i in range(5)
        ])

        charge_label = Text("+ outside, - inside", font_size=18, color=GRAY)
        charge_label.to_edge(DOWN)

        self.play(Write(rest_text))
        self.play(Write(plus_outside), Write(minus_inside))
        self.play(Write(charge_label))
        self.wait(1)

        self.plus_signs = plus_outside
        self.minus_signs = minus_inside
        self.rest_text = rest_text
        self.charge_label = charge_label

    def animate_action_potential(self):
        # Update title
        ap_text = Text("Action Potential Propagates →", font_size=28, color=YELLOW)
        ap_text.to_edge(UP)
        self.play(Transform(self.rest_text, ap_text))

        # Create propagating wave
        wave = Circle(radius=0.3, fill_opacity=0.8, fill_color=YELLOW, stroke_color=ORANGE)
        wave.move_to(self.soma.get_center())

        self.play(Create(wave))

        # Animate wave traveling along axon
        path_points = [
            self.soma.get_right(),
            self.axon.get_left() + RIGHT * 2,
            self.axon.get_center(),
            self.axon.get_right() - RIGHT * 2,
            self.terminal.get_left()
        ]

        for i, point in enumerate(path_points):
            # Flash at each position
            flash = Circle(radius=0.5, fill_opacity=0, stroke_color=YELLOW, stroke_width=4)
            flash.move_to(point)

            self.play(
                wave.animate.move_to(point),
                Create(flash),
                run_time=0.5
            )
            self.play(FadeOut(flash), run_time=0.2)

        # Wave reaches terminal
        self.play(
            wave.animate.scale(1.5),
            Flash(self.terminal, color=YELLOW)
        )

        signal_text = Text("Signal transmitted!", font_size=24, color=GREEN)
        signal_text.next_to(self.terminal, UP)
        self.play(Write(signal_text))

        self.wave = wave
        self.signal_text = signal_text

    def show_voltage_graph(self):
        # Clear some elements
        self.play(
            FadeOut(self.plus_signs),
            FadeOut(self.minus_signs),
            FadeOut(self.charge_label),
            FadeOut(self.wave),
            FadeOut(self.signal_text),
            self.neuron_group.animate.shift(UP * 1.5).scale(0.7)
        )

        # Create voltage vs time graph
        axes = Axes(
            x_range=[0, 5, 1],
            y_range=[-80, 50, 20],
            x_length=8,
            y_length=4,
            axis_config={"include_tip": True},
        ).shift(DOWN * 1)

        x_label = Text("Time (ms)", font_size=18).next_to(axes.x_axis, DOWN)
        y_label = Text("Voltage (mV)", font_size=18).next_to(axes.y_axis, LEFT).rotate(90 * DEGREES)

        self.play(Create(axes), Write(x_label), Write(y_label))

        # Action potential curve
        def ap_curve(t):
            if t < 1:
                return -70  # Resting
            elif t < 1.5:
                return -70 + 140 * (t - 1) / 0.5  # Depolarization
            elif t < 2:
                return 40 - 120 * (t - 1.5) / 0.5  # Repolarization
            elif t < 2.5:
                return -80 + 10 * (t - 2) / 0.5  # Hyperpolarization
            else:
                return -70  # Return to resting

        graph = axes.plot(ap_curve, x_range=[0, 4], color=YELLOW)

        # Animate the graph drawing
        self.play(Create(graph), run_time=3)

        # Labels for phases
        phases = [
            ("Resting", 0.5, -70, WHITE),
            ("Depolarization", 1.25, 0, GREEN),
            ("Peak (+40mV)", 1.5, 40, RED),
            ("Repolarization", 1.75, -20, BLUE),
            ("Hyperpolarization", 2.25, -80, PURPLE),
        ]

        for name, x, y, color in phases:
            point = axes.c2p(x, y)
            dot = Dot(point, color=color)
            label = Text(name, font_size=14, color=color)
            label.next_to(dot, UP if y > -50 else DOWN, buff=0.2)
            self.play(Create(dot), Write(label), run_time=0.5)

        self.wait(1)


if __name__ == "__main__":
    # Render with: manim -pql action_potential.py ActionPotentialScene
    pass
