"""
Synaptic Transmission
Generated by LearnViz

Visualizes how signals cross from one neuron to another.
"""
from manim import *

class SynapseScene(Scene):
    def construct(self):
        # Title
        title = Text("Synaptic Transmission", font_size=42)
        subtitle = Text("How neurons communicate", font_size=24, color=GRAY)
        subtitle.next_to(title, DOWN)

        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)
        self.play(FadeOut(title), FadeOut(subtitle))

        # Create synapse structure
        self.create_synapse()
        self.wait(1)

        # Animate signal arrival
        self.signal_arrives()
        self.wait(0.5)

        # Vesicle release
        self.release_neurotransmitters()
        self.wait(0.5)

        # Receptor binding
        self.receptor_binding()
        self.wait(2)

    def create_synapse(self):
        # Presynaptic terminal (top)
        self.presynaptic = RoundedRectangle(
            width=4, height=2, corner_radius=0.3,
            fill_opacity=0.7, fill_color=BLUE, stroke_color=WHITE
        ).shift(UP * 2)
        pre_label = Text("Presynaptic Terminal", font_size=18).next_to(self.presynaptic, UP)

        # Vesicles inside presynaptic
        self.vesicles = VGroup()
        for i in range(6):
            vesicle = Circle(radius=0.15, fill_opacity=0.8, fill_color=YELLOW, stroke_color=ORANGE)
            vesicle.move_to(self.presynaptic.get_center() + UP * 0.3 + LEFT * 0.8 + RIGHT * i * 0.3)
            self.vesicles.add(vesicle)

        # Synaptic cleft (gap)
        self.cleft = Rectangle(
            width=4.5, height=0.8,
            fill_opacity=0.2, fill_color=WHITE, stroke_color=GRAY
        )
        cleft_label = Text("Synaptic Cleft", font_size=16, color=GRAY).next_to(self.cleft, LEFT)

        # Postsynaptic membrane (bottom)
        self.postsynaptic = RoundedRectangle(
            width=4, height=1.5, corner_radius=0.3,
            fill_opacity=0.7, fill_color=GREEN, stroke_color=WHITE
        ).shift(DOWN * 2)
        post_label = Text("Postsynaptic Neuron", font_size=18).next_to(self.postsynaptic, DOWN)

        # Receptors on postsynaptic membrane
        self.receptors = VGroup()
        for i in range(5):
            receptor = Rectangle(width=0.2, height=0.4, fill_opacity=0.8, fill_color=RED, stroke_color=WHITE)
            receptor.move_to(self.postsynaptic.get_top() + LEFT * 1 + RIGHT * i * 0.5)
            self.receptors.add(receptor)

        receptor_label = Text("Receptors", font_size=14, color=RED).next_to(self.receptors, RIGHT)

        self.play(
            Create(self.presynaptic), Write(pre_label),
            Create(self.vesicles)
        )
        self.play(Create(self.cleft), Write(cleft_label))
        self.play(
            Create(self.postsynaptic), Write(post_label),
            Create(self.receptors), Write(receptor_label)
        )

    def signal_arrives(self):
        # Action potential arrives
        signal = Text("⚡ Action Potential Arrives!", font_size=24, color=YELLOW)
        signal.to_edge(UP)
        self.play(Write(signal))

        # Flash the presynaptic terminal
        self.play(
            self.presynaptic.animate.set_fill(YELLOW, opacity=0.9),
            Flash(self.presynaptic, color=YELLOW),
            run_time=0.5
        )
        self.play(
            self.presynaptic.animate.set_fill(BLUE, opacity=0.7),
            run_time=0.3
        )

        self.signal_text = signal

    def release_neurotransmitters(self):
        # Update text
        release_text = Text("Vesicles release neurotransmitters", font_size=20, color=ORANGE)
        release_text.to_edge(UP)
        self.play(Transform(self.signal_text, release_text))

        # Vesicles move to membrane and release
        released = VGroup()
        for i, vesicle in enumerate(self.vesicles[:3]):
            # Move vesicle to bottom of presynaptic
            self.play(
                vesicle.animate.move_to(self.presynaptic.get_bottom()),
                run_time=0.3
            )
            # "Release" - create small dots representing neurotransmitters
            for j in range(4):
                nt = Dot(radius=0.05, color=YELLOW)
                nt.move_to(vesicle.get_center())
                released.add(nt)
                target = self.cleft.get_center() + LEFT * 0.5 + RIGHT * j * 0.3 + DOWN * 0.2 * (i + 1)
                self.play(
                    nt.animate.move_to(target),
                    run_time=0.2
                )
            self.play(FadeOut(vesicle), run_time=0.1)

        self.neurotransmitters = released

    def receptor_binding(self):
        # Update text
        bind_text = Text("Neurotransmitters bind to receptors", font_size=20, color=GREEN)
        bind_text.to_edge(UP)
        self.play(Transform(self.signal_text, bind_text))

        # Move neurotransmitters to receptors
        for i, nt in enumerate(self.neurotransmitters[:5]):
            if i < len(self.receptors):
                target = self.receptors[i].get_top()
                self.play(nt.animate.move_to(target), run_time=0.3)
                self.play(self.receptors[i].animate.set_fill(YELLOW, opacity=0.9), run_time=0.2)

        # Signal continues
        continue_text = Text("Signal continues in postsynaptic neuron!", font_size=22, color=GREEN)
        continue_text.next_to(self.postsynaptic, DOWN, buff=0.5)
        self.play(
            self.postsynaptic.animate.set_fill(YELLOW, opacity=0.7),
            Write(continue_text)
        )
        self.play(self.postsynaptic.animate.set_fill(GREEN, opacity=0.7))


if __name__ == "__main__":
    # Render with: manim -pql synapse.py SynapseScene
    pass
